//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardPatient.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patients()
        {
            this.visitHistory = new HashSet<visitHistory>();
        }
    
        
        public int id { get; set; }
        [Required(ErrorMessage = "Это поле обязательно для заполнения")]
        [Range(1, 999999999999, ErrorMessage = "Неверно введен ИИН")]
        public string uin { get; set; }
        [Required(ErrorMessage = "Это поле обязательно для заполнения")]
        [StringLength(50)]
        public string address { get; set; }
        [Required(ErrorMessage = "Это поле обязательно для заполнения")]
        [StringLength(12, ErrorMessage = "Номер телефона не может превышать 12 символов")]  
        public string phone { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Это поле обязательно для заполнения")]
        public string firstName { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Это поле обязательно для заполнения")]
        public string lastName { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Это поле обязательно для заполнения")]
        public string patronymic { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitHistory> visitHistory { get; set; }
    }
}
