//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardPatient.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class visitHistory
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Это поле обязательно для заполнения")]

        public Nullable<int> patient_id { get; set; }
        [Required(ErrorMessage = "Это поле обязательно для заполнения")]

        public Nullable<int> specialty_id { get; set; }
        [Required(ErrorMessage = "Это поле обязательно для заполнения")]

        public Nullable<int> doctor_id { get; set; }
        [Required(ErrorMessage = "Это поле обязательно для заполнения")]

        public Nullable<int> diagnosis_id { get; set; }
        [Required(ErrorMessage = "Это поле обязательно для заполнения")]

        public string complaints { get; set; }
        [Required(ErrorMessage = "Это поле обязательно для заполнения")]

        public Nullable<System.DateTime> date { get; set; }

        public virtual diagnoses diagnoses { get; set; }

        public virtual doctors doctors { get; set; }

        public virtual patients patients { get; set; }

        public virtual specialties specialties { get; set; }
    }
}
